apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: clusterroles-session-rules
parameters:
- name: NAME_PREFIX
  value: ""
  required: false
- name: WORKSHOP_NAME
  value: ""
  required: true
- name: SPAWNER_NAMESPACE
  value: ""
  required: true
- name: SPAWNER_MODE
  value: "learning-portal"
  required: true
objects:
- apiVersion: authorization.openshift.io/v1
  kind: ClusterRole
  metadata:
    name: ${NAME_PREFIX}${WORKSHOP_NAME}-session-rules
    labels:
      app: ${NAME_PREFIX}${WORKSHOP_NAME}
      spawner: ${SPAWNER_MODE}
      class: spawner
  rules:
  - apiGroups:
    - "tekton.dev"
    resources:
    - clustertasks
    - pipelineresources
    - pipelines
    - pipelineruns
    - tasks
    - taskruns
    verbs:
    - get
    - list
    - watch
    - create
    - delete
    - patch
    - update
  - apiGroups:
    - "operator.tekton.dev"
    resources:
    - config
    verbs:
    - get
    - list
    - watch
    - create
    - delete
    - patch
    - update
  - apiGroups:
    - ""
    - security.openshift.io
    resources:
    - securitycontextconstraints
    verbs:
    - create
    - delete
    - deletecollection
    - get
    - list
    - patch
    - update
    - watch
