apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: configmap-session-resources
parameters:
- name: NAME_PREFIX
  value: ""
  required: false
- name: WORKSHOP_NAME
  value: ""
  required: true
- name: SPAWNER_NAMESPACE
  value: ""
  required: true
- name: SPAWNER_MODE
  value: "learning-portal"
  required: true
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    name: ${NAME_PREFIX}${WORKSHOP_NAME}-session-resources
    labels:
      app: ${NAME_PREFIX}${WORKSHOP_NAME}
      spawner: ${SPAWNER_MODE}
      class: spawner
  data:
    extra_resources.yaml: |-
        kind: List
        apiVersion: v1
        items:
        - kind: ServiceAccount
          apiVersion: v1
          metadata:
            name: pipeline
        - kind: ClusterRole
          apiVersion: rbac.authorization.k8s.io/v1
          metadata:
            name: ${project_namespace}-pipelines
          rules:
          - apiGroups:
            - security.openshift.io
            resources:
            - securitycontextconstraints
            verbs:
            - use
            resourceNames:
            - privileged
        - kind: RoleBinding
          apiVersion: rbac.authorization.k8s.io/v1
          metadata:
            name: pipelines-privileged-scc
          subjects:
          - kind: ServiceAccount
            name: pipeline
            namespace: "${project_namespace}"
          roleRef:
            kind: ClusterRole
            apiGroup: rbac.authorization.k8s.io
            name: ${project_namespace}-pipelines
        - kind: RoleBinding
          apiVersion: rbac.authorization.k8s.io/v1
          metadata:
            name: pipelines-project-edit
          subjects:
          - kind: ServiceAccount
            name: pipeline
            namespace: "${project_namespace}"
          roleRef:
            kind: ClusterRole
            apiGroup: rbac.authorization.k8s.io
            name: edit
